apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::018738447678:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-W9LG4KG4UUB9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::018738447678:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-14T00:06:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6131"
  uid: 3fb30641-7acb-4d5a-b206-f7d2220aef68
